apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: test
  namespace: test-namespace
  labels:
    app.kubernetes.io/name: flais-test-application
    app.kubernetes.io/instance: flais-test-application_rogfk_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: test-application
    app.kubernetes.io/part-of: flais
    fintlabs.no/team: flais
    fintlabs.no/org-id: rogfk.no
spec:
  port: 8080
  orgId:
  image: docker/getting-started
  imagePullPolicy: Always
  prometheus:
    enabled: true
    port: "80"
    path: /prometheus
  env:
    - name: ENV1
      value: test
  envFrom:
    - secretRef:
        name: secret-test
  onePassword:
    itemPath: ""
  kafka:
    enabled: true
    acls:
      - topic: ''
        permission: read
  database:
    database: fint-test
  url:
    hostname: test.io
    basePath: /
  ingress:
    enabled: true
    middlewares: []
  resources:
    limits:
      memory: "1024Mi"
      cpu: "250m"
    requests:
      memory: "128Mi"
      cpu: "100m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }